### ISSUE TITLE
漏洞：通过下界传送门切换维度时发生游戏卡死

### ISSUE THREAD

**Issue by HamdsomeAtom125** [SourceLandDev/.github#13]
### 操作系统

未知/平台无关

### Minecraft版本

1.20.31

### 描述漏洞

在玩家从进入下界传送门前往下界时，有极高概率一直卡在“生成世界中”界面。
此时如果强制退出游戏并重进，你会发现你传送到了下界，但坐标与你所在上一个维度的坐标一致。

例如：你在主世界80000 80 80000进入了地狱，而你触发了这个bug。此时如果你重启游戏并重进服务器，你会发现你进入了下界，但坐标不是10000 80 10000，而是跟主世界一样（既80000 80 80000）。

更为严重的是，如果你是从下界传送回主世界，那么也会触发卡在“生成世界中”的bug，但是当你尝试重进服务器的时候，玩家将再也无法进入服务器，且提示“连接到世界出现问题”。（目前玩家小鹿呀已经出现该问题。该玩家的截图于附加上下文）

### 重现步骤

1. 进入下界门
2. （有较大概率）触发此bug

### 预期行为

进入下界传送门进行维度切换

### 附加上下文
![IMG_0503](https://github.com/SourceLandDev/.github/assets/100036558/5ac1120a-ecd6-4858-8a4b-69b43da58d4b)

**Comment by HamdsomeAtom125** [comment]
经确认，玩家lsjzssx22因触发bug也遭遇了无法连接服务器的问题。

**Comment by Hosiyume** [comment]
需要补充

**Comment by HamdsomeAtom125** [comment]
此问题触发具有随机性
玩家**正常**进入下界后 bug就有概率出现
无法继续补充

猜测有以下几种情况：
1.下界或主世界的地图数据存在问题
2.系统判断玩家传送位置时发生错误
3.玩家进入需要传送的维度时，加载附近区块发生错误

**Comment by HamdsomeAtom125** [comment]
属实 用户小鹿呀已可正常游戏
之后将尝试使用内容日志文件进行上报

**Comment by Hosiyume** [comment]
https://bugs.mojang.com/browse/MCPE-173386
