### ISSUE TITLE
漏洞：通过物品快递发送粉红色花瓣物品时发生错误

### ISSUE THREAD

**Issue by HamdsomeAtom125** [SourceLandDev/.github#14]
### 操作系统

未知/平台无关

### Minecraft版本

1.20.31

### 描述漏洞

使用物品快递向他人发出一组粉红色花瓣后，系统显示的发送数值存在问题，并且扣除了大量经验值。

更加离谱的是，我的背包里仅放了一组花瓣，却发出了两组花瓣。而正常发送其他物品没有该问题。

此bug猜测与实验性玩法有关。原因是服务器在1.19版本就已经通过实验性玩法启动了1.20的樱花树玩法。

### 重现步骤

1.输入命令/menu
2.打开功能菜单后打开快递菜单
3.向他人发送一组粉红色花瓣
4.bug产生

### 预期行为

向他人正常发生粉红色花瓣这一物品。

### 附加上下文

个人使用的编辑器发生问题，无法正常插入图片。此为图片直链：
https://img.xhacgn.com/images/2023/10/08/Screenshot_2023-10-08-08-16-50-529_com.mojang.minecraftpe.jpg

**Comment by HamdsomeAtom125** [comment]
已知道问题根源 此为MC本体的拖动条错误。

**Comment by HamdsomeAtom125** [comment]
将上报至mojira。

**Comment by HamdsomeAtom125** [comment]
该漏洞的触发并非上文的重现步骤。
如果需要可以留言

**Comment by Hosiyume** [comment]
#15
