### ISSUE TITLE
功能：关于对于绑定诅咒南瓜头的解决办法

### ISSUE THREAD

**Issue by 13736074794** [SourceLandDev/.github#2]
### 您的功能请求是否与问题有关？请描述一下。

请腐竹大大帮我把这个破南瓜头使用clear命令清除掉
![Screenshot_2023-09-10-09-34-27-97_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/SourceLandDev/.github/assets/145248665/d28a5586-ffdb-4c05-b4c4-f30447e3a7b8)

### 描述您想要的解决方案

使用clear命令清除背包物品

### 描述你考虑过的替代方案

暂无

### 附加上下文

暂无

**Comment by 13736074794** [comment]
QwQxinlei6

**Comment by Hosiyume** [comment]
现在死亡后会掉落绑定诅咒物品
