### ISSUE TITLE
功能：关闭服务器实验性玩法

### ISSUE THREAD

**Issue by HamdsomeAtom125** [SourceLandDev/.github#23]
### 您的功能请求是否与问题有关？请描述一下。

[来源于baldr Ray]
实验性玩法导致村民交易的附魔书成品质量下降，影响了游戏体验。

### 描述您想要的解决方案

关闭实验性玩法

### 附加上下文

baldr Ray录制的视频，用以辅助说明该操作可行：
http://sdly.blockelite.cn:15021/web/client/pubshares/7jAnN6Yj7iXYA5tsrJYNxK?compress=false

**Comment by Hosiyume** [comment]
鉴于mojang的代码质量，关闭开启过的实验性特性可能会导致存档不稳定
