### ISSUE TITLE
下线：关于服务器无法进入的事项

### ISSUE THREAD

**Issue by 13736074794** [SourceLandDev/.github#3]
### 操作系统

未知/平台无关

### Minecraft版本

1.20.5

### 描述漏洞

服务器无法进入，不知如何原因

### 重现步骤

![Screenshot_2023-09-17-11-14-50-05_84d3000e3f4017145260f7618db1d683](https://github.com/SourceLandDev/.github/assets/145248665/269cbda7-73ff-4486-ba6a-4c234b9bef87)

### 预期行为

希望早日能修复

**Comment by Hosiyume** [comment]
服务器禁ping

**Comment by Hosiyume** [comment]
疑似Windows Server预览版的时间炸弹
