### ISSUE TITLE
漏洞：吃东西瞬移，以及反复回弹，这是以前从没出现过的现象

### ISSUE THREAD

**Issue by long27829** [SourceLandDev/.github#39]
### 操作系统

Android

### Minecraft版本

1.20.40

### 描述漏洞

在吃东西时移动，会以极其低的帧率进行瞬移，使用鞘翅时会经常莫名其妙落在地上，或是起飞后被直接拉回地面

### 重现步骤

食用任意食物时移动
在地上使用激流三叉戟，或是在天上飞行时

### 预期行为

希望能修复到跟以前一样（应该不会是mojang的代码问题吧）

**Comment by Hosiyume** [comment]
1.20.51测试已修复，请等待服务器更新

**Comment by Hosiyume** [comment]
移动校验已被暂时禁用
