### ISSUE TITLE
漏洞：1.20.40-1.20.51客户端无法连接服务器

### ISSUE THREAD

**Issue by HamdsomeAtom125** [SourceLandDev/.github#47]
### 服务

未知/所有

### 附加上下文

![Screenshot_2024-01-11-22-06-00-459_com tencent mobileqq](https://github.com/SourceLandDev/.github/assets/123252860/fa4a129a-c283-4ed6-b7da-fcf1f3776d30)

**Comment by Hosiyume** [comment]
https://github.com/GlacieTeam/Glacie-Release/issues/2
