### ISSUE TITLE
漏洞：弩使用异常

### ISSUE THREAD

**Issue by long27829** [SourceLandDev/.github#56]
### 操作系统

Android

### Minecraft版本

1.20.50

### 描述漏洞

弩在长按装填箭时，有几率出现连发bug（如果可控倒还是好事，但是这玩意没法控制）

### 重现步骤

1.手机版
2.新触控
3.拿着弩长按使用

### 预期行为

希望能完全修复

### 附加上下文

无

**Comment by Hosiyume** [comment]
请先尝试能否于客户端复现

**Comment by Hosiyume** [comment]
> > 请先尝试能否于客户端复现
> 
> 
> 
> 可以，重进多次依然存在

请反馈至Mojira
