### ISSUE TITLE
漏洞：副手拿取光源物品时方块被吞

### ISSUE THREAD

**Issue by HamdsomeAtom125** [SourceLandDev/.github#6]
### 操作系统

Windows

### Minecraft版本

1.20.30

### 描述漏洞

副手不可正常拿取光源物品，且光源物品会被吞

### 重现步骤

将光源物品（如火把、灯）放置副手位置时会不起作用

此时重进服务器或用其他物品（如箭、烟花）放置到副手时，光源物品会被吞掉

### 预期行为

将光源物品放置于副手

**Comment by Hosiyume** [comment]
[移动光源](https://github.com/SourceLandDev/DynamicLight)暂时下线
