### ISSUE TITLE
功能：可以通过网站等方式查看世界地图

### ISSUE THREAD

**Issue by HamdsomeAtom125** [SourceLandDev/.github#8]
### 您的功能请求是否与问题有关？请描述一下。

现在我正在建设全新的长途A线——这是一条就目前而言整个服务器最长的铁路，目前达到了16000格，目标是想通过铁路连接起各个领地，从而能使各个领地能更好往来合作，同时也能欣赏沿途的风景。
可问题也就出现了——到底如何能确定各个领地的位置呢？
故此也便产生了想随时访问最新的世界地图的想法。

### 描述您想要的解决方案

之前腐竹也使用过存档直接生成地图。那么能否更近一步，能够每天自动更新一次地图，并且可以通过访问特定的网站来查看地图呢？
其实有很多服务器有了这个功能 所以我认为这个功能应该是可以实现的

### 描述你考虑过的替代方案

比如直接想腐竹要地图然后生成……但是这样第一是太过麻烦了，腐竹每天有很多的事情要忙。第二也是注意到服务器添加了隐藏地图种子的功能，所以也能猜测出腐竹不想让我们通过种子来确定那些自然生成的建筑物，比如末地城。（不过我只是想查看主世界的地图，像末地这样的高价值地图可以不提供地图服务）

**Comment by Hosiyume** [comment]
易泄漏坐标

**Comment by HamdsomeAtom125** [comment]
> 易泄漏坐标

能明白是为了安全性 可以理解
